spring:
  application:
    name: Deal
  datasource:
    url: jdbc:postgresql://localhost:5432/calculator_db
    username: admin
    password: pass
    driverClassName: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
    liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.xml
  cloud:
    openfeign:
      client:
        config:
          calculator:
            url: http://localhost:8088/calculator
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
server:
  port: 8089
logging:
  level:
    root: INFO
