spring:
  application:
    name: Deal
  datasource:
    url: jdbc:postgresql://postgres:5432/calculator_db
    username: admin
    password: pass
    driverClassName: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
    liquibase:
      enabled: true
      change-log: classpath:/db/changelog/db.changelog-master.yaml
  cloud:
    openfeign:
      client:
        config:
          calculator:
            url: http://calculator-service:8080/calculator
  kafka:
    bootstrap-servers: ${BROKER_HOST:localhost}:9092
server:
  port: 8081
logging:
  level:
    root: INFO
