spring:
  application:
    name: Statement
  cloud:
    openfeign:
      client:
        config:
          deal:
            url: http://deal-service:8081/deal
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
server:
  port: 8084

logging:
  level:
    root: INFO
