spring:
  application:
    name: Statement
  cloud:
    openfeign:
      client:
        config:
          deal:
            url: http://localhost:8089/deal
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
server:
  port: 8090
  servlet:
    context-path: /StatementAPI

logging:
  level:
    root: INFO
