spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: deal-service
          uri: http://deal-service:8081
          predicates:
            - Path=/deal/**
          filters:
            - StripPrefix=0
        - id: statement-service
          uri: http://statement-service:8084
          predicates:
            - Path=/statement/**
          filters:
            - StripPrefix=0
    openfeign:
      client:
        config:
          deal:
            url: http://deal-service:8081/deal
          statement:
            url: http://statement-service:8084/statement
server:
  port: 8083
logging:
  level:
    root: INFO