spring:
  application:
    name: Gateway
  cloud:
    openfeign:
      client:
        default-to-properties: true
        config:
          deal:
            url: http://deal:9001/deal
          statement:
            url: http://statement:9002/statement
server:
  port: 8087

logging:
  level:
    root: INFO
