spring:
  application:
    name: Gateway
  cloud:
    openfeign:
      client:
        default-to-properties: true
        config:
          deal:
            url: http://deal-service:8081/deal
          statement:
            url: http://statement-service:8084/statement
server:
  port: 8083

logging:
  level:
    root: INFO
