spring:
  application:
    name: Gateway
  cloud:
    openfeign:
      client:
        default-to-properties: true
        config:
          deal:
            url: http://${DEAL_HOST:localhost}:8081/deal
          statement:
            url: http://${STATEMENT_HOST:localhost}:8084/statement
server:
  port: 8083

logging:
  level:
    root: INFO
