spring:
#  main:
#    web-application-type: reactive
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: deal-service
          uri: http://localhost:8089
          predicates:
            - Path=/deal/**
          filters:
            - StripPrefix=1
        - id: statement-service
          uri: http://localhost:8090
          predicates:
            - Path=/statement/**
          filters:
            - StripPrefix=1
    openfeign:
      client:
        config:
          deal:
            url: http://localhost:8089/deal
          statement:
            url: http://localhost:8090/statement
server:
  port: 8087
logging:
  level:
    root: INFO