spring:
  application:
    name: Gateway
  cloud:
    openfeign:
      client:
        config:
          deal:
            url: http://localhost:8089/deal
          statement:
            url: http://localhost:8090/statement
server:
  port: 8087

logging:
  level:
    root: INFO
