spring:
  application:
    name: Calculator
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null
server:
  port: 8080

logging:
  level:
    root: INFO
