spring:
  application:
    name: Dossier
  mail:
    host: smtp.gmail.com
    port: 587
    username: YouMail
    password: Pass
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  kafka:
      bootstrap-servers: dossier-service:9092
  cloud:
    openfeign:
      client:
        config:
          deal:
            url: http://deal-service:8081/deal
server:
  port: 8082

logging:
  level:
    root: INFO
